### PR TITLE
Support for unlimited users

### PR DESCRIPTION
**Pull request by snozzley**
Hi,
Thanks for your addon, it's been really helpful.
As I have a growing family, I required more users.  Rather than increasing the static list, I've made it a dynamic list, so you can support any number of users now.
Each user must have their own range (defined by GT/LT), and if they overlap, then it will just match on the first valid one it finds.

Not sure what the ENV variable part was used for, so I haven't touched that just yet.

Tested on my own hassio and working well.

Let me know what you think

### CODE REVIEW

**Comment by lolouk44** [comment]
Thanks for your help.
I'm quite busy with my work at the moment so can't look at this right now in detail, but I had a glance at the change and so far it looks good so will defo look / test once I get some spare time...

**Comment by snozzley** [comment]
Thanks, yeah probably needs a bit of tidy up still - like with the ENV variables?
I'm also thinking maybe instead of having GT LT, just setting a 'base weight' type value, and assuming they are within say 10 or 20kg of that range?
Anyways, no hurry in reviewing, I've got it running on my hassio for now, so I'm happy :)

**Comment by lolouk44** [comment]
The ENV variables are for people not using an add-on but a standard docker container. Was trying to keep everything in 1 package to reduce maintenance, but now I've come to realise I have to duplicate everything I do in both repos 🤔

**Comment by fufar** [comment]
that will be great. i have only 2 users, but by default i need 3

**Comment by lolouk44** [comment]
Hey. Sorry it took so long.
It was quite a change and as a result I ended up fixing other things and now your code is too old.
I've copied your code and changed where necessary, but it means I can't accept your PR as it is
I've tested your code and it works great for me at least, I'll be sure to add you to the Thank You list :)
0.1.19 on its way soon

**Comment by lolouk44** [comment]
Changed my mind, I thought it as big enough a change/enhancement to move to [0.2.0](https://github.com/lolouk44/hassio-addons/releases/tag/0.2.0) 😃

**Comment by snozzley** [comment]
New release works really well, thanks for that!

**Pull request closed without merging**
